AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS BMI SAM template
Resources:
  ApiFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.main
      Runtime: python3.8
      CodeUri: ./code
      Description: 'Lambda function to calculate BMI'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::894653739574:role/service-role/wendy-bmi-lambda-role-ymhgesk6'
      Events:
        ApiEvent:
          Type: Api
          Properties: 
            Path: /getBMI
            Method: get
      Environment:
        Variables:
          REGION: ap-southeast-1
      
